import type { GroceryAiExtraction } from "../ai/token-mapper";
import type { GroceryItem } from "../../domain/grocery-item";

export interface SharedTestCase {
	id: string; // Unique kebab-case ID
	description: string; // Human-readable description
	input: string; // Raw Swedish text
	expected_ai_extraction: Partial<GroceryAiExtraction>; // Expected AI extraction
	expected_grocery_item: Partial<GroceryItem>; // Expected final GroceryItem
	critical?: boolean; // Mark as critical test
}

// Shared test cases for both manual and AI parsers
// Copied from audit-test-cases.ts with added expected GroceryItem output
export const SHARED_TEST_CASES: SharedTestCase[] = [
	{
		id: "basic-organic-milk",
		description: "Basic quantity, unit, item with organic modifier",
		input: "2 paket ekologisk mjölk",
		expected_ai_extraction: {
			raw_text: "2 paket ekologisk mjölk",
			raw_item: "mjölk",
			raw_qty: "2",
			raw_unit: "paket",
			raw_brand: null,
			raw_modifiers: ["ekologisk"],
			raw_offer: null,
			raw_size_value: null,
			raw_size_unit: null,
			raw_comment: null,
		},
		expected_grocery_item: {
			item: "mjölk",
			category: "mejeri",
			quantity: 2,
			quantity_unit: "st",
			size_value: 0,
			size_unit: null,
			brand: null,
			organic: true,
			comment: null,
			unit_normalized: null,
			total_quantity_value: 2,
			total_quantity_unit: "paket",
			store_normalized: null,
			store_raw: null,
			offer_quantity: 0,
			offer_total_price_value: 0,
			offer_currency: null,
			offer_unit_price_value: 0,
		},
		critical: true,
	},
	{
		id: "weight-based-potato",
		description: "Weight-based item",
		input: "1 kg potatis",
		expected_ai_extraction: {
			raw_text: "1 kg potatis",
			raw_item: "potatis",
			raw_qty: "1",
			raw_unit: "kg",
			raw_brand: null,
			raw_modifiers: [],
			raw_offer: null,
			raw_size_value: null,
			raw_size_unit: null,
			raw_comment: null,
		},
		expected_grocery_item: {
			item: "potatis",
			category: "frukt & grönt",
			quantity: 0,
			quantity_unit: null,
			size_value: 1,
			size_unit: "kg",
			brand: null,
			organic: false,
			comment: null,
			unit_normalized: null,
			total_quantity_value: 1,
			total_quantity_unit: "kg",
			store_normalized: null,
			store_raw: null,
			offer_quantity: 0,
			offer_total_price_value: 0,
			offer_currency: null,
			offer_unit_price_value: 0,
			status: "ok",
			error: null,
			source: "manual",
		},
		critical: true,
	},
	{
		id: "countable-eggs",
		description: "Countable item with 'st' unit",
		input: "6 st ägg",
		expected_ai_extraction: {
			raw_text: "6 st ägg",
			raw_item: "ägg",
			raw_qty: "6",
			raw_unit: "st",
			raw_brand: null,
			raw_modifiers: [],
			raw_offer: null,
			raw_size_value: null,
			raw_size_unit: null,
			raw_comment: null,
		},
		expected_grocery_item: {
			item: "ägg",
			category: "mejeri",
			quantity: 6,
			quantity_unit: "st",
			size_value: 0,
			size_unit: null,
			brand: null,
			organic: false,
			comment: null,
			unit_normalized: null,
			total_quantity_value: 6,
			total_quantity_unit: "st",
			store_normalized: null,
			store_raw: null,
			offer_quantity: 0,
			offer_total_price_value: 0,
			offer_currency: null,
			offer_unit_price_value: 0,
			status: "ok",
			error: null,
			source: "manual",
		},
		critical: true,
	},
	{
		id: "container-canned-tomatoes",
		description: "Container unit with multi-word item",
		input: "1 burk krossade tomater",
		expected_ai_extraction: {
			raw_text: "1 burk krossade tomater",
			raw_item: "krossade tomater",
			raw_qty: "1",
			raw_unit: "burk",
			raw_brand: null,
			raw_modifiers: [],
			raw_offer: null,
			raw_size_value: null,
			raw_size_unit: null,
			raw_comment: null,
		},
		expected_grocery_item: {
			item: "tomat",
			category: "frukt & grönt",
			quantity: 1,
			quantity_unit: "burk",
			size_value: 0,
			size_unit: null,
			brand: null,
			organic: false,
			comment: "krossade",
			unit_normalized: null,
			total_quantity_value: 1,
			total_quantity_unit: "st",
			store_normalized: null,
			store_raw: null,
			offer_quantity: 0,
			offer_total_price_value: 0,
			offer_currency: null,
			offer_unit_price_value: 0,
			status: "ok",
			error: null,
			source: "manual",
		},
		critical: true,
	},
	{
		id: "weight-no-quantity-spaghetti",
		description: "Weight without explicit quantity",
		input: "500 g spaghetti",
		expected_ai_extraction: {
			raw_text: "500 g spaghetti",
			raw_item: "spaghetti",
			raw_qty: null,
			raw_unit: null,
			raw_brand: null,
			raw_modifiers: [],
			raw_offer: null,
			raw_size_value: "500",
			raw_size_unit: "g",
			raw_comment: null,
		},
		expected_grocery_item: {
			item: "spaghetti",
			category: "skafferi",
			quantity: 0,
			quantity_unit: null,
			size_value: 500,
			size_unit: "g",
			brand: null,
			organic: false,
			comment: null,
			unit_normalized: null,
			total_quantity_value: 500,
			total_quantity_unit: "g",
			store_normalized: null,
			store_raw: null,
			offer_quantity: 0,
			offer_total_price_value: 0,
			offer_currency: null,
			offer_unit_price_value: 0,
			status: "ok",
			error: null,
			source: "manual",
		},
		critical: true,
	},
	{
		id: "volume-unit-cream",
		description: "Volume unit",
		input: "3 dl grädde",
		expected_ai_extraction: {
			raw_text: "3 dl grädde",
			raw_item: "grädde",
			raw_qty: "3",
			raw_unit: "dl",
			raw_brand: null,
			raw_modifiers: [],
			raw_offer: null,
			raw_size_value: null,
			raw_size_unit: null,
			raw_comment: null,
		},
		expected_grocery_item: {
			item: "grädde",
			category: "mejeri",
			quantity: 3,
			quantity_unit: "dl",
			size_value: 0,
			size_unit: null,
			brand: null,
			organic: false,
			comment: null,
			unit_normalized: null,
			total_quantity_value: 3,
			total_quantity_unit: "dl",
			store_normalized: null,
			store_raw: null,
			offer_quantity: 0,
			offer_total_price_value: 0,
			offer_currency: null,
			offer_unit_price_value: 0,
			status: "ok",
			error: null,
			source: "manual",
		},
		critical: true,
	},
	{
		id: "container-oil-bottle",
		description: "Container unit with oil",
		input: "1 flaska olivolja",
		expected_ai_extraction: {
			raw_text: "1 flaska olivolja",
			raw_item: "olivolja",
			raw_qty: "1",
			raw_unit: "flaska",
			raw_brand: null,
			raw_modifiers: [],
			raw_offer: null,
			raw_size_value: null,
			raw_size_unit: null,
			raw_comment: null,
		},
		expected_grocery_item: {
			item: "olivolja",
			category: "skafferi",
			quantity: 1,
			quantity_unit: "flaska",
			size_value: 0,
			size_unit: null,
			brand: null,
			organic: false,
			comment: null,
			unit_normalized: null,
			total_quantity_value: 1,
			total_quantity_unit: "st",
			store_normalized: null,
			store_raw: null,
			offer_quantity: 0,
			offer_total_price_value: 0,
			offer_currency: null,
			offer_unit_price_value: 0,
			status: "ok",
			error: null,
			source: "manual",
		},
		critical: true,
	},
	{
		id: "simple-packet-yeast",
		description: "Simple packet item",
		input: "2 pkt jäst",
		expected_ai_extraction: {
			raw_text: "2 pkt jäst",
			raw_item: "jäst",
			raw_qty: "2",
			raw_unit: "pkt",
			raw_brand: null,
			raw_modifiers: [],
			raw_offer: null,
			raw_size_value: null,
			raw_size_unit: null,
			raw_comment: null,
		},
		expected_grocery_item: {
			item: "jäst",
			category: "skafferi",
			quantity: 2,
			quantity_unit: "pkt",
			size_value: 0,
			size_unit: null,
			brand: null,
			organic: false,
			comment: null,
			unit_normalized: null,
			total_quantity_value: 2,
			total_quantity_unit: null,
			store_normalized: null,
			store_raw: null,
			offer_quantity: 0,
			offer_total_price_value: 0,
			offer_currency: null,
			offer_unit_price_value: 0,
			status: "ok",
			error: null,
			source: "manual",
		},
		critical: true,
	},
	{
		id: "single-vegetable-cucumber",
		description: "Single vegetable",
		input: "1 st gurka",
		expected_ai_extraction: {
			raw_text: "1 st gurka",
			raw_item: "gurka",
			raw_qty: "1",
			raw_unit: "st",
			raw_brand: null,
			raw_modifiers: [],
			raw_offer: null,
			raw_size_value: null,
			raw_size_unit: null,
			raw_comment: null,
		},
		expected_grocery_item: {
			item: "gurka",
			category: "frukt & grönt",
			quantity: 1,
			quantity_unit: "st",
			size_value: 0,
			size_unit: null,
			brand: null,
			organic: false,
			comment: null,
			unit_normalized: null,
			total_quantity_value: 1,
			total_quantity_unit: "st",
			store_normalized: null,
			store_raw: null,
			offer_quantity: 0,
			offer_total_price_value: 0,
			offer_currency: null,
			offer_unit_price_value: 0,
			status: "ok",
			error: null,
			source: "manual",
		},
		critical: true,
	},
	{
		id: "no-unit-bananas",
		description: "Item without explicit unit",
		input: "4 bananer",
		expected_ai_extraction: {
			raw_text: "4 bananer",
			raw_item: "bananer",
			raw_qty: "4",
			raw_unit: null,
			raw_brand: null,
			raw_modifiers: [],
			raw_offer: null,
			raw_size_value: null,
			raw_size_unit: null,
			raw_comment: null,
		},
		expected_grocery_item: {
			item: "banan",
			category: "frukt & grönt",
			quantity: 4,
			quantity_unit: null,
			size_value: 0,
			size_unit: null,
			brand: null,
			organic: false,
			comment: null,
			unit_normalized: null,
			total_quantity_value: 4,
			total_quantity_unit: null,
			store_normalized: null,
			store_raw: null,
			offer_quantity: 0,
			offer_total_price_value: 0,
			offer_currency: null,
			offer_unit_price_value: 0,
			status: "ok",
			error: null,
			source: "manual",
		},
		critical: true,
	},
	{
		id: "brand-with-size-zeta",
		description: "Brand with size specification",
		input: "Zeta olivolja 500 ml",
		expected_ai_extraction: {
			raw_text: "Zeta olivolja 500 ml",
			raw_item: "olivolja",
			raw_qty: null,
			raw_unit: null,
			raw_brand: "Zeta",
			raw_modifiers: [],
			raw_offer: null,
			raw_size_value: "500",
			raw_size_unit: "ml",
			raw_comment: null,
		},
		expected_grocery_item: {
			item: "olivolja",
			category: "skafferi",
			quantity: 0,
			quantity_unit: null,
			size_value: 500,
			size_unit: "ml",
			brand: "Zeta",
			organic: false,
			comment: null,
			unit_normalized: null,
			total_quantity_value: 500,
			total_quantity_unit: "ml",
			store_normalized: null,
			store_raw: null,
			offer_quantity: 0,
			offer_total_price_value: 0,
			offer_currency: null,
			offer_unit_price_value: 0,
			status: "ok",
			error: null,
			source: "manual",
		},
		critical: true,
	},
	{
		id: "organic-with-store-banana",
		description: "Organic item with store reference",
		input: "1 st ekologisk banan från Coop",
		expected_ai_extraction: {
			raw_text: "1 st ekologisk banan från Coop",
			raw_item: "banan",
			raw_qty: "1",
			raw_unit: "st",
			raw_brand: null,
			raw_modifiers: ["ekologisk"],
			raw_offer: null,
			raw_size_value: null,
			raw_size_unit: null,
			raw_comment: "från Coop",
		},
		expected_grocery_item: {
			item: "banan",
			category: "frukt & grönt",
			quantity: 1,
			quantity_unit: "st",
			size_value: 0,
			size_unit: null,
			brand: null,
			organic: true,
			comment: "från Coop",
			unit_normalized: null,
			total_quantity_value: 1,
			total_quantity_unit: "st",
			store_normalized: "Coop",
			store_raw: "coop",
			offer_quantity: 0,
			offer_total_price_value: 0,
			offer_currency: null,
			offer_unit_price_value: 0,
			status: "ok",
			error: null,
			source: "manual",
		},
		critical: true,
	},
	// Additional test cases for comprehensive coverage
	{
		id: "complex-milk-offer",
		description:
			"Complex line with quantity, size, brand, organic, offer, and store",
		input: "3 pkt 1,5l mjölk eko arla 4/50kr ica",
		expected_ai_extraction: {
			raw_text: "3 pkt 1,5l mjölk eko arla 4/50kr ica",
			raw_item: "mjölk",
			raw_qty: "3",
			raw_unit: "pkt",
			raw_brand: "arla",
			raw_modifiers: ["eko"],
			raw_offer: "4/50kr",
			raw_size_value: "1.5",
			raw_size_unit: "l",
			raw_comment: null,
		},
		expected_grocery_item: {
			item: "mjölk",
			category: "mejeri",
			quantity: 3,
			quantity_unit: "pkt",
			size_value: 1.5,
			size_unit: "l",
			brand: "Arla",
			organic: true,
			comment: null,
			unit_normalized: null,
			total_quantity_value: 4.5,
			total_quantity_unit: "l",
			store_normalized: "ICA",
			store_raw: "ica",
			offer_quantity: 4,
			offer_total_price_value: 50,
			offer_currency: "SEK",
			offer_unit_price_value: 12.5,
			status: "ok",
			error: null,
			source: "manual",
		},
		critical: true,
	},
	{
		id: "simple-item-default",
		description: "Simple item without quantity - should default to 1 st",
		input: "mjölk",
		expected_ai_extraction: {
			raw_text: "mjölk",
			raw_item: "mjölk",
			raw_qty: null,
			raw_unit: null,
			raw_brand: null,
			raw_modifiers: [],
			raw_offer: null,
			raw_size_value: null,
			raw_size_unit: null,
			raw_comment: null,
		},
		expected_grocery_item: {
			item: "mjölk",
			category: "mejeri",
			quantity: 1,
			quantity_unit: "st",
			size_value: 0,
			size_unit: null,
			brand: null,
			organic: false,
			comment: null,
			unit_normalized: null,
			total_quantity_value: 1,
			total_quantity_unit: "st",
			store_normalized: null,
			store_raw: null,
			offer_quantity: 0,
			offer_total_price_value: 0,
			offer_currency: null,
			offer_unit_price_value: 0,
			status: "ok",
			error: null,
			source: "manual",
		},
		critical: true,
	},
	{
		id: "unknown-item",
		description: "Unknown item should return needs_review status",
		input: "okänd produkt",
		expected_ai_extraction: {
			raw_text: "okänd produkt",
			raw_item: "okänd produkt",
			raw_qty: null,
			raw_unit: null,
			raw_brand: null,
			raw_modifiers: [],
			raw_offer: null,
			raw_size_value: null,
			raw_size_unit: null,
			raw_comment: null,
		},
		expected_grocery_item: {
			item: "okänd produkt",
			category: null,
			quantity: 1,
			quantity_unit: "st",
			size_value: 0,
			size_unit: null,
			brand: null,
			organic: false,
			comment: null,
			unit_normalized: null,
			total_quantity_value: 1,
			total_quantity_unit: "st",
			store_normalized: null,
			store_raw: null,
			offer_quantity: 0,
			offer_total_price_value: 0,
			offer_currency: null,
			offer_unit_price_value: 0,
			status: "needs_review",
			error: null,
			source: "manual",
		},
		critical: true,
	},
];

export function generate_test_id(description: string): string {
	return description
		.toLowerCase()
		.replace(/[^a-z0-9\s-]/g, "")
		.replace(/\s+/g, "-")
		.substring(0, 50);
}
