import type { GroceryAiExtraction } from '../token-mapper';

export interface TestCase {
  id: string;              // Unique kebab-case ID
  description: string;     // Human-readable description
  input: string;           // Raw Swedish text
  expected: Partial<GroceryAiExtraction>;  // Inline expected values
  critical?: boolean;      // Mark as critical test
}

// Ported from parsing-integration.test.ts TEST_CASES
export const AUDIT_TEST_CASES: TestCase[] = [
  {
    id: 'basic-organic-milk',
    description: 'Basic quantity, unit, item with organic modifier',
    input: '2 paket ekologisk mjölk',
    expected: {
      raw_text: '2 paket ekologisk mjölk',
      raw_item: 'mjölk',
      raw_qty: '2',
      raw_unit: 'paket',
      raw_brand: null,
      raw_modifiers: ['ekologisk'],
      raw_offer: null,
      raw_size_value: null,
      raw_size_unit: null,
      raw_comment: null,
    },
    critical: true,
  },
  {
    id: 'weight-based-potato',
    description: 'Weight-based item',
    input: '1 kg potatis',
    expected: {
      raw_text: '1 kg potatis',
      raw_item: 'potatis',
      raw_qty: '1',
      raw_unit: 'kg',
      raw_brand: null,
      raw_modifiers: [],
      raw_offer: null,
      raw_size_value: null,
      raw_size_unit: null,
      raw_comment: null,
    },
    critical: true,
  },
  {
    id: 'countable-eggs',
    description: "Countable item with 'st' unit",
    input: '6 st ägg',
    expected: {
      raw_text: '6 st ägg',
      raw_item: 'ägg',
      raw_qty: '6',
      raw_unit: 'st',
      raw_brand: null,
      raw_modifiers: [],
      raw_offer: null,
      raw_size_value: null,
      raw_size_unit: null,
      raw_comment: null,
    },
    critical: true,
  },
  {
    id: 'container-canned-tomatoes',
    description: 'Container unit with multi-word item',
    input: '1 burk krossade tomater',
    expected: {
      raw_text: '1 burk krossade tomater',
      raw_item: 'krossade tomater',
      raw_qty: '1',
      raw_unit: 'burk',
      raw_brand: null,
      raw_modifiers: [],
      raw_offer: null,
      raw_size_value: null,
      raw_size_unit: null,
      raw_comment: null,
    },
    critical: true,
  },
  {
    id: 'weight-no-quantity-spaghetti',
    description: 'Weight without explicit quantity',
    input: '500 g spaghetti',
    expected: {
      raw_text: '500 g spaghetti',
      raw_item: 'spaghetti',
      raw_qty: null,
      raw_unit: null,
      raw_brand: null,
      raw_modifiers: [],
      raw_offer: null,
      raw_size_value: '500',
      raw_size_unit: 'g',
      raw_comment: null,
    },
    critical: true,
  },
  {
    id: 'volume-unit-cream',
    description: 'Volume unit',
    input: '3 dl grädde',
    expected: {
      raw_text: '3 dl grädde',
      raw_item: 'grädde',
      raw_qty: '3',
      raw_unit: 'dl',
      raw_brand: null,
      raw_modifiers: [],
      raw_offer: null,
      raw_size_value: null,
      raw_size_unit: null,
      raw_comment: null,
    },
    critical: true,
  },
  {
    id: 'container-oil-bottle',
    description: 'Container unit with oil',
    input: '1 flaska olivolja',
    expected: {
      raw_text: '1 flaska olivolja',
      raw_item: 'olivolja',
      raw_qty: '1',
      raw_unit: 'flaska',
      raw_brand: null,
      raw_modifiers: [],
      raw_offer: null,
      raw_size_value: null,
      raw_size_unit: null,
      raw_comment: null,
    },
    critical: true,
  },
  {
    id: 'simple-packet-yeast',
    description: 'Simple packet item',
    input: '2 pkt jäst',
    expected: {
      raw_text: '2 pkt jäst',
      raw_item: 'jäst',
      raw_qty: '2',
      raw_unit: 'pkt',
      raw_brand: null,
      raw_modifiers: [],
      raw_offer: null,
      raw_size_value: null,
      raw_size_unit: null,
      raw_comment: null,
    },
    critical: true,
  },
  {
    id: 'single-vegetable-cucumber',
    description: 'Single vegetable',
    input: '1 st gurka',
    expected: {
      raw_text: '1 st gurka',
      raw_item: 'gurka',
      raw_qty: '1',
      raw_unit: 'st',
      raw_brand: null,
      raw_modifiers: [],
      raw_offer: null,
      raw_size_value: null,
      raw_size_unit: null,
      raw_comment: null,
    },
    critical: true,
  },
  {
    id: 'no-unit-bananas',
    description: 'Item without explicit unit',
    input: '4 bananer',
    expected: {
      raw_text: '4 bananer',
      raw_item: 'bananer',
      raw_qty: '4',
      raw_unit: null,
      raw_brand: null,
      raw_modifiers: [],
      raw_offer: null,
      raw_size_value: null,
      raw_size_unit: null,
      raw_comment: null,
    },
    critical: true,
  },
  {
    id: 'brand-with-size-zeta',
    description: 'Brand with size specification',
    input: 'Zeta olivolja 500 ml',
    expected: {
      raw_text: 'Zeta olivolja 500 ml',
      raw_item: 'olivolja',
      raw_qty: null,
      raw_unit: null,
      raw_brand: 'Zeta',
      raw_modifiers: [],
      raw_offer: null,
      raw_size_value: '500',
      raw_size_unit: 'ml',
      raw_comment: null,
    },
    critical: true,
  },
  {
    id: 'organic-with-store-banana',
    description: 'Organic item with store reference',
    input: '1 st ekologisk banan från Coop',
    expected: {
      raw_text: '1 st ekologisk banan från Coop',
      raw_item: 'banan',
      raw_qty: '1',
      raw_unit: 'st',
      raw_brand: null,
      raw_modifiers: ['ekologisk'],
      raw_offer: null,
      raw_size_value: null,
      raw_size_unit: null,
      raw_comment: 'från Coop',
    },
    critical: true,
  },
];

export function generate_test_id(description: string): string {
  return description
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .substring(0, 50);
}
