ALTER TABLE `grocery_list` ADD COLUMN `store` text;
ALTER TABLE `grocery_list_item` ADD COLUMN `input_raw` text NOT NULL DEFAULT '';
ALTER TABLE `grocery_list_item` ADD COLUMN `item` text;
ALTER TABLE `grocery_list_item` ADD COLUMN `quantity_unit` text;
ALTER TABLE `grocery_list_item` ADD COLUMN `size_value` real;
ALTER TABLE `grocery_list_item` ADD COLUMN `size_unit` text;
ALTER TABLE `grocery_list_item` ADD COLUMN `brand` text;
ALTER TABLE `grocery_list_item` ADD COLUMN `organic` integer DEFAULT false NOT NULL;
ALTER TABLE `grocery_list_item` ADD COLUMN `status` text DEFAULT 'needs_review' NOT NULL;
ALTER TABLE `grocery_list_item` ADD COLUMN `position` integer DEFAULT 0 NOT NULL;
DROP INDEX `grocery_list_item_name_unique`;
